title: Anneke Slis
description: Speech Science | Motor Control | Dysarthria | Stuttering | EMA
logo: /assets/images/profile_picture_2.jpg
theme: jekyll-theme-minimal

show_downloads: false

markdown: kramdown

plugins:
  - jekyll-seo-tag

