title: Anneke Slis
description: Speech Science | Motor Control | Dysarthria | Stuttering | EMA
logo: /assets/images/_C1A9513.jpg

theme: jekyll-theme-minimal

show_downloads: false

markdown: kramdown

plugins:
  - jekyll-seo-tag

